# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-linuxfb"
BBFILE_PATTERN_meta-linuxfb = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-linuxfb = "10"

LAYERDEPENDS_meta-linuxfb = "core qt6-layer"
LAYERSERIES_COMPAT_meta-linuxfb = "scarthgap"
